### ISSUE TITLE
Mysql table with multiple primary keys?

### ISSUE THREAD

**Issue by hyperbolic2346** [bsteph/FFLLogbook#31]
What sql database are you using that allows multiple primary keys? I'm trying to get this setup, but I'm running into trouble importing the schema.

**Comment by bsteph** [comment]
mysql 5.7

**Comment by hyperbolic2346** [comment]
Interesting. I'm using 5.7.14:
```
Server version: 5.7.14 MySQL Community Server (GPL)
```
and getting this on import:
```
mysql ffl -u ffl -p < ffl.sql
Enter password:
ERROR 1068 (42000) at line 35: Multiple primary key defined
```
Are you using innodb?

**Comment by bsteph** [comment]
My apologies.  I was developing using mariadb.  I was able to recreate the issue using a mysql instance.  I dropped the additional primary keys and created multiple indexes.  Code has been updated.

**Comment by bsteph** [comment]
Please let me know if that fixes the issue for you.
